### PR TITLE
add number of exceptions to hazard score output

### PR DESCRIPTION
**Pull request by dhosterman**
This adds the number of exceptions to hazards in the output json file of a run. It should be sufficient to direct an interested party to the forthcoming journal for additional data, as well as to populate the web interface with a numeric indication of issues that may have occurred during the run.

### CODE REVIEW

**Review by wpietri — APPROVED** [review]
Looks good as is, but I'm not sure exceptions is the precise thing to count at this level, in that we may end up with more ways for something to not be usable. For example, if our annotators have low confidence, we might just not count the item in the score. So maybe want to count two of a) total items started, b) items successfully process, and c) items unsuccessfully processed.

**Review by rogthefrog — APPROVED** [review]

**Comment by rogthefrog** [comment]
Unrelated to these changes: are the `Hazard.score()` calls expensive, and would they benefit from memoization?

**Review by bkorycki — APPROVED** [review]
I think this will be very useful! I also like William's suggestion of broadening the scope to capture items skipped for any reason, not just exceptions. Maybe the fields can be `num_items_scored` and `num_items_skipped`?

**Comment by wpietri** [comment]
> Unrelated to these changes: are the `Hazard.score()` calls expensive, and would they benefit from memoization?

They are not expensive. They're pretty simple calculations on top of the test scores.

**Pull request merged**
