### PR TITLE
Rewrite docs for public launch.

### PR DESCRIPTION
**Pull request by wpietri**
Add context, clean up examples, explain new features.

Note that this doesn't include how to run your own SUT; support for that will come in a later PR.

### CODE REVIEW

**Comment by bollacker** [comment]
Fixed two typos.

**Review by bollacker — APPROVED** [review]
LGTM

**Review by wpietri — COMMENTED** [review]
Thanks!

**Comment by wpietri** [comment]
Although the initial part has been merged, still happy to take feedback, Daniel and Yifan. I just wanted to get something out there for the morning.

**Pull request merged**
